### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by DVergil** [leem919/xcloud-pwa#1]
Hello, I would like to test this pwa on my amazon fire tv.
How can I make it work?

**Comment by leem919** [comment]
A quick Google search makes it seem like I have to develop an app for this, which would be difficult since I don't own a fire TV. Plus, there may be an existing browser I don't know about, so I'd suggest looking for one. Sorry I can't help

**Comment by DVergil** [comment]
a complication in apk of this link serious great

**Comment by DVergil** [comment]
I recommend searching for "xcloud shield tv" here on github and taking it as a base to create an apk using this link from your pwa

**Comment by leem919** [comment]
Well, I can make an attempt at developing it directly for the Amazon platform, because I've discovered that Amazon web app testing exists for normal androids

**Comment by DVergil** [comment]
Good

**Comment by DVergil** [comment]
however, are you going to use their cloud gaming as a base to make the apk?

**Comment by DVergil** [comment]
I saw that it works as a pwa apk too

**Comment by DVergil** [comment]
Basically like an apk that you install through a browser, but it is in the official amazon store

**Comment by leem919** [comment]
Hey by the way, thanks for creating this issue. You brought to my attention the fact that my code doesn't seem to be working as it should anymore for some reason. However, that also means I need to get that fixed up first before I get into Amazon TV stuff.

**Comment by DVergil** [comment]
no, on the contrary it is really working well on my smartphone

**Comment by DVergil** [comment]
However I wanted to know if you are going to update the project

**Comment by leem919** [comment]
I don't have much more to update, unless you had a little something in mind, also I'm talking about installing the app. I had trouble recently with the prompt showing up, and my friend had the same. You can manually activate it on Chrome, but I couldn't find a way to do it on the Samsung browser

**Comment by DVergil** [comment]
I was only able to add it to the home screen by Samsung

**Comment by DVergil** [comment]
In Chrome the installation is much easier

**Comment by leem919** [comment]
Well I did some testing, and the android tv doesn't seem too happy with xcloud
![image](https://user-images.githubusercontent.com/8106607/216762829-20f5c709-c183-41bf-8910-12e6d17ef8bf.png)
However, if you're willing to sideload Aptoide, there's the Xbox Gamepass app available with cloud gaming built into it. As far as I'm aware, you just can't play fortnite with it lol

**Comment by DVergil** [comment]
that's the only problem.

**Comment by DVergil** [comment]
Fortnite is only available in the browser version

**Comment by DVergil** [comment]
Can I recommend you an xcloud project to use as a base?

**Comment by DVergil** [comment]
It works well, but it hasn't been updated in almost two years and it has bugs and things that haven't been fixed.

**Comment by DVergil** [comment]
I think an update would fix a lot of things

**Comment by DVergil** [comment]
I believe that the big problem is that the android TV system practically does not have a browser

**Comment by DVergil** [comment]
I tested the geforce now app on my amazon fire stick and it runs very well

**Comment by DVergil** [comment]
However, I believe that the application runs natively and with the internal components ready to do this

**Comment by DVergil** [comment]
Unfortunately the xcloud app doesn't work well nor do we own the android system

**Comment by DVergil** [comment]
On Android TV it has no native support and runs sadly

**Comment by DVergil** [comment]
For now the best version of xcloud at least for me is the one made for 2022 Samsung TVs and Edge and Chrome Browser

**Comment by DVergil** [comment]
I believe that Microsoft from the beginning wanted to support more browser version

**Comment by DVergil** [comment]
Since even on a very good connection, the application still has several problems

**Comment by DVergil** [comment]
While geforce now runs at 1080p60 on my amazon on not very good internet with the best mbps rate and quality possible.
xcloud is not so lucky and works poorly in application, browser
